name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2025
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1

    steps:
    - uses: actions/checkout@main

    - name: Update Submodules
      run: git submodule update --init --recursive --jobs $env:NUMBER_OF_PROCESSORS

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      id: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload a Build Artifact
      if: steps.build.outcome == 'success'
      uses: actions/upload-artifact@main
      with:
        name: xenos_recomp_windows
        path: ${{github.workspace}}/build
        if-no-files-found: error
